server:
  port: 8090
spring:
  cloud:
    gateway:
      routes:
      - id: api-route
        uri: http://localhost:8123
        predicates:
          - Path=/api/**

# 服务注册
dubbo:
  application:
    name: nacos-registry-consumer
  registry:
    address: nacos://localhost:8848

logging:
  level:
    org.springframework.cloud.gateway: debug