spring:
  application:
    name: kabigon-api
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://nj-cynosdbmysql-grp-hrn5jbix.sql.tencentcdb.com:22734/kabigon_api
    username: root
    password: Ew~E6p;GbK7l
    hikari:
      minimum-idle: 3
      maximum-pool-size: 5
      max-lifetime: 0
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  # redis 配置
  redis:
    port: 6379
    host: 43.142.22.140
    database: 0
    password:
server:
  port: 7529
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
# 接口安全校验
#kabigon:
#  api:
#    access-key: kabigon
#    secret-key: asdfghjkl
dubbo:
  application:
    name: nacos-registry-provider
  registry:
    address: nacos://localhost:8848
